apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: podlister
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
